extends: substitution
message: "Please use '%s' instead of '%s'."
link: 'https://developers.google.com/style/inclusive-documentation'
ignorecase: true
level: error
swap:
  blacklist(?:ed|s|ing|\b): denylist
  whitelist(?:ed|s|ing|\b): allowlist
  native: built-in
  master: main
  slave: subordinate
